In [1]:
print("Hello! Let's learn Pytorch!")



Hello! Let's learn Pytorch!


https://www.learnpytorch.io/00_pytorch_fundamentals/


In [2]:
import torch
torch.__version__

'1.10.2'

Introduction to tensors
- tensors represent data in a numerical way 
- example: image with shape - [3, 224, 224] is [colour_channels, height, width]
    - 3 colour channels 
    - 224 pixels height 
    - 224 pixels width


# Creating Tensors

In [6]:
#scalar - zero dimension tensor - single number 
scalar = torch.tensor(7)
scalar
#prints out a torch.Tensor of a single number 

#check the dimensions
scalar.ndim

#retrieve the items in the tensor - this also turns the tensor into a python int
scalar.item()

7

In [9]:
#vector - single dimension tensoor - can only contain numbers 
vector = torch.tensor([7,7])
vector

#check dimensions 
vector.ndim

#shape - tells us the arrangement of the items 
vector.shape


torch.Size([2])

In [13]:
#matrix - more flexiable than vectors
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX
#check the dimnesions 
MATRIX.ndim
#check the shape
MATRIX.shape
#2 rows 2 columns 

torch.Size([2, 2])

In [17]:
#tensor - can represent more variations of data
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR
#Key difference between a matrix and tensor - tensor can be n-dimensions
TENSOR.ndim

#check the shape
TENSOR.shape
#Result: torch.Size([1, 3, 3]
#So this means we have a 1 dimension matrix of 3 by 3. [DIM, ROWS, COLUMNS]

torch.Size([1, 3, 3])

In [18]:
#Creating random tensors 
random_tensor = torch.rand(size = (3,4))
random_tensor, random_tensor.dtype

(tensor([[0.1128, 0.6776, 0.7646, 0.7227],
         [0.7722, 0.5252, 0.9267, 0.2778],
         [0.1261, 0.9261, 0.7601, 0.1713]]),
 torch.float32)

In [19]:
#Creating a zero matrix 
zeros = torch.zeros(size = (3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [21]:
#Creting a matrix one matrix
ones = torch.ones(size = (1,3,4))
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [25]:
#Creating a range
#(start, end, step)
rangeTens = torch.arange(1,10, 1)
rangeTens

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#Creating a tensor similar to antoher one 
similarTens = torch.zeros_like(rangeTens)
similarTens
#creates a vector with the same shape of 0's

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes
- torch.cuda, the tensor is being used for a GPU 
- common type: torch.float
- pytorch likes computations to be done on the same devices 

In [28]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [29]:
#Getting information about a tensor 
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.1208, 0.5198, 0.3464, 0.3361],
        [0.8449, 0.9478, 0.1717, 0.7674],
        [0.2776, 0.6549, 0.1261, 0.1593]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Basic Operations


In [30]:
#adding 
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [31]:
#multiply
tensor * 10

tensor([10, 20, 30])

In [32]:
#subtraction 
tensor - 10

tensor([-9, -8, -7])

Element wise multiplication 
- (2,3) @ (3, 2) works 
- (3, 2) @ (2, 3) will not work 

In [36]:
#element wise: 
tensor * tensor

tensor([1, 4, 9])

In [34]:
#matmul
torch.matmul(tensor, tensor)
#[1 * 1 + 2 * 2 + 3 * 3] = [14]
#basically a dot product

tensor(14)

# Linear Layer

Equation: y = x * A^T + b 
- x is the input later 
- A is the weight matrix, which needs to be transposed 
- b is the bias term to offset the weights and inputs
- y is the output

In [41]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [40]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 

                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


# Aggregation

In [42]:
x = torch.arange(0, 100, 10)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [43]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

# Reshaping, stacking, squezzing, and unsqueezing 

In [47]:
x = torch.arange(1., 8.)
x.shape

torch.Size([7])

In [46]:
#add another dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [52]:
#stacking 
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [55]:
#indexing 
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")


First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [61]:
#Gpu check 

print(torch.version.cuda)

None


In [60]:
pip install torch torchvision torchaudio -f https://download.pytorch.org/whl/cu111/torch_stable.html

Looking in links: https://download.pytorch.org/whl/cu111/torch_stable.html
     |████████████████████████████████| 2.4 MB 1.8 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.
